project:
  type: website
  output-dir: docs

website:
  title: "ggplot2 extenders 🫖"
  reader-mode: true
  repo-url: https://github.com/teunbrand/ggplot-extension-club
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: discussion.qmd
        text: Discuss
      - href: meetings.qmd
        text: Meet
      - href: additional-resources.qmd
        text: More Resources

    tools:
      - icon: github
        href: https://github.com/teunbrand/ggplot-extension-club
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gina Reynolds, Teun van den Brand"

format:
  html:
    theme: theme.scss
    toc: true

editor: source
